### PR TITLE
#291 change `throw error` to `return null`

### PR DESCRIPTION
**Pull request by lijiarui**
#291 
if Contact&Room cannot find, function `fnd()` return null

### CODE REVIEW

**Comment by lijiarui** [comment]
@zixia added jsDoc as you required

**Comment by zixia** [comment]
Thanks!

**Comment by lijiarui** [comment]
#291

**Comment by lijiarui** [comment]
After merged this one, the following code doesn't work
```
example/gist-bot/on-friend.ts(34,9): error TS2531: Object is possibly 'null'.
example/gist-bot/on-friend.ts(35,9): error TS2531: Object is possibly 'null'.
example/gist-bot/on-message.ts(40,11): error TS2531: Object is possibly 'null'.
example/gist-bot/on-message.ts(46,7): error TS2531: Object is possibly 'null'.
```

**Comment by zixia** [comment]
Then fix it please.

**Pull request merged**
