### PR TITLE
add the methods' doc link

### PR DESCRIPTION
**Pull request by TbhT**

### CODE REVIEW

**Comment by TbhT** [comment]
Add the corresponding doc link for most methods.

**Comment by zixia** [comment]
However, it seems that this pull request is conflict with the code base 

Could you please fix the conflict before we can be able to better it?

**Comment by TbhT** [comment]
Seems that i have no write access to merge the PR.

**Comment by TbhT** [comment]
Oh,  i have sync the changes to latest version.

**Comment by zixia** [comment]
Awesome.

Thank you very much for the contribution!

**Pull request merged**
