### PR TITLE
feat<PuppetPuppeteer>:add chrome executable path when initialize wechaty

### PR DESCRIPTION
**Pull request by htoooth**
## Description

Add executable chrome path in order to use custom chrome exe.

## Does this PR introduce a breaking change?

No

### CODE REVIEW

**Comment by zixia** [comment]
Thanks for the PR.

We are heavy refactoring the Puppet system right now, will discuss it with you later when we finished the v0.16.

**Comment by zixia** [comment]
Hi @htoooth 

Sorry for the delay before I could be able to discuss your PR with you.

Currently, we had almost finish refactored the Puppet System, and I believe it's the time to merge your PR because later we will split the PuppetPuppeteer out of the Wechaty as a solo npm module: http://github.com/chatie/wechaty-puppet-puppeteer

Could you please have a look at the latest design of the Puppet System? The good start could be from here:

https://github.com/Chatie/wechaty/blob/7aaa42b6211bb0527eb51dbab15ef512dac819d4/src/puppet/schemas/puppet.ts#L64-L69

And because there's already an option key named `endpoint`, I feel it will suitable to be used to set the chrome executable path.

**Comment by htoooth** [comment]
@zixia  Thanks.  I will try.

**Comment by zixia** [comment]
Awesome.

I'll postpone splitting the puppet-puppeteer module out of the Wechaty before merge your PR.

Looking forward to your update.

**Comment by zixia** [comment]
We had just moved this module to a new repository at <https://github.com/chatie/wechaty-puppet-puppeteer>, please re-submit your PR over there.

Sorry for the inconvenience, but I hope you could understand because we are in heavy refactoring processes now.

See: #1371

**Comment by zixia** [comment]
ping @htoooth 

Could we make this PR to fit the new puppet this month?

**Pull request closed without merging**
