### PR TITLE
William doc dev

### PR DESCRIPTION
**Pull request by kis87988**
add comment to room.ts,message.ts into documentation.

### CODE REVIEW

**Comment by lijiarui** [comment]
I suggest keeping the origin format, please change the format and just keep the doc modify here, thanks!

**Comment by zixia** [comment]
Thanks! Please:
1. Follow the review from @lijiarui 
1. Get at least three votes(approved) from our contributor team

Our document needs to be improved heavily and continuously.

**Comment by kis87988** [comment]
I redo again with original format, please review it again.

**Comment by zixia** [comment]
I understand that your PR had been merged into @lijiarui's #725, so I'm very appreciated for your contributing and want to say thank you very much to you.

**Comment by kis87988** [comment]
No problem, I will keep watch if need to add docs future.

**Pull request closed without merging**
