### PR TITLE
Update `room-invite` signature documentation

### PR DESCRIPTION
**Pull request by xinbenlv**
## I'm submitting a...

```
[ ] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by xinbenlv** [comment]
Shippable failure is unrelated.

**Comment by xinbenlv** [comment]
ping~

**Comment by lijiarui** [comment]
LGTM，How about @huan

**Comment by huan** [comment]
@lijiarui I don't think so.

The `docs/index.md` is generated from `src/**/*.ts`, which means that we should never modify it directly.

What @xinbenlv want to fix should be at the location of:

https://github.com/Chatie/wechaty/blob/21ff9ca288c610d96e69c20eb836874344afc717/src/wechaty.ts#L374-L375

**Comment by lijiarui** [comment]
@huan Yes, you are right. I forgot this.

**Comment by huan** [comment]
ping @xinbenlv

**Comment by huan** [comment]
kindly ping @xinbenlv

**Comment by xinbenlv** [comment]
Sorry missed this notification.

**Comment by xinbenlv** [comment]
Replaced by #1814

**Pull request closed without merging**
